Drop old patterns. We use meta packages.
sailfish-sdk/sailfish-api-patterns pull request #5
Opened 2021-06-04 05:06 UTC by saukko

[patterns] Drop old patterns. Contributes to JB#53606

Signed-off-by: Marko Saukko <marko.saukko@jolla.com>

2021-06-04 05:54 UTC, vigejolla approved these changes
LGTM

2021-06-04 07:15 UTC, mkosola approved these changes

2021-06-09 09:30 UTC, sledges requested changes
Please nuke the [patterns/](https://github.com/sailfishos/sailfish-api-patterns/tree/master/patterns) directory altogether.

2021-06-09 11:52 UTC, sledges approved these changes

2021-06-09 15:04 UTC, merged